// @vitest-environment happy-dom
import { describe, it, expect, beforeEach } from 'vitest';
import { SimilarityEngine } from '../utils/SimilarityEngine';

describe('SimilarityEngine', () => {
  beforeEach(() => {
    document.body.innerHTML = `
      <div id="list">
        <ul>
          <li class="item">
            <div class="card">
               <span class="title">Item 1</span>
               <span class="price">$10</span>
            </div>
          </li>
          <li class="item">
            <div class="card">
               <span class="title">Item 2</span>
               <span class="price">$20</span>
            </div>
          </li>
          <li class="item">
             <div class="card">
               <span class="title">Item 3</span>
               <span class="price">$30</span>
             </div>
          </li>
          <li class="other">
             <span>Ignored</span>
          </li>
        </ul>
      </div>
    `;
  });

  it('should find similar elements based on relaxed structural matching', () => {
    // Select first title
    const firstTitle = document.querySelector('.title') as HTMLElement;

    // Fake selector as if generated by SelectorEngine (it might be specific path)
    // ul > li:nth-child(1) > div > span.title
    const selector = 'ul > li:nth-child(1) > div > span';

    const similar = SimilarityEngine.findSimilar(firstTitle, selector);

    // Should find all 3 titles
    expect(similar.length).toBe(3);
    expect(similar[0].textContent).toBe('Item 1');
    expect(similar[1].textContent).toBe('Item 2');
    expect(similar[2].textContent).toBe('Item 3');
  });

  it('should exclude elements with vastly different structures', () => {
    document.body.innerHTML = `
            <ul class="list">
                <li class="item"><span>Price: $10</span></li>
                <li class="item"><span>Price: $20</span></li>
                <li class="item"><a href="#">Link instead</a></li>
            </ul>
        `;
    const root = document.querySelector('span')!;
    const similar = SimilarityEngine.findSimilar(root, 'ul > li > span');

    // Should find the other span, but NOT the 'a' tag even though they are cousins
    expect(similar.length).toBe(2);
    expect(similar[1].textContent).toBe('Price: $20');
  });

  it('should handle nested repetitive structures (tables)', () => {
    document.body.innerHTML = `
            <table>
                <tbody>
                    <tr><td>Data 1</td></tr>
                    <tr><td>Data 2</td></tr>
                    <tr><td>Data 3</td></tr>
                </tbody>
            </table>
        `;
    const root = document.querySelector('td')!;
    const similar = SimilarityEngine.findSimilar(root, 'table > tbody > tr > td');
    expect(similar.length).toBe(3);
  });

  it('should handles prices correctly', () => {
    const firstPrice = document.querySelector('.price') as HTMLElement;
    const selector = 'ul > li:nth-child(1) > div > span.price'; // Hypothetical selector

    const similar = SimilarityEngine.findSimilar(firstPrice, selector);
    expect(similar.length).toBe(3);
    expect(similar.map(el => el.textContent)).toEqual(['$10', '$20', '$30']);
  });
});
